# Archivo: .github/workflows/ci.yml
name: CI - UltraPro16

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Validar estilo de código (ESLint)
        run: |
          if [ -f .eslintrc.js ]; then
            npx eslint . || true
          else
            echo "No se encontró ESLint, se omite lint."
          fi

      - name: Ejecutar tests
        run: |
          if [ -f package.json ] && grep -q '"test":' package.json; then
            npm test || true
          else
            echo "No hay tests definidos."
          fi

      - name: Generar archivo .env.example seguro
        run: |
          if [ -f .env ]; then
            grep -v 'SMTP_PASS\|SLACK_BOT_TOKEN\|SLACK_WEBHOOK_URL' .env > .env.example
            echo "Archivo .env.example generado (credenciales sensibles ocultas)"
          else
            echo "No hay .env para generar ejemplo"
          fi

      - name: Build del proyecto
        run: |
          if [ -f package.json ] && grep -q '"build":' package.json; then
            npm run build
          else
            echo "No hay script de build definido"
          fi

      - name: Auditoría de dependencias
        run: npm audit --audit-level=moderate

      - name: Confirmar archivos críticos
        run: |
          [ -f index.js ] && echo "✅ index.js existe"
          [ -f barrera.js ] && echo "✅ barrera.js existe"
          [ -f run16.sh ] && echo "✅ run16.sh existe"
          [ -f panel.sh ] && echo "✅ panel.sh existe"
          [ -d public ] && echo "✅ carpeta public existe"
